# Financial Inclusion


## ACCESS_FINANCIAL_ALL
Ever used formal financial services - counts respondents who:
    Have a bank account registered in thier name or a joint account registered in their name and someone's else or 
    Use a bank account that belongs to someone else or 
    Ever used a mobile money service or a non-bank financial institution for any financial activity. 

Levels:

+ Yes
+ No
    
## ACCESS_FINANCIAL 
Ever used full-service formal financial services: counts the same respondents as for variable ACCESS_FINANCIAL_ALL but uses only full-service banks and non-bank financial institutions. 

Levels: 

+ Yes
+ No

## FI
Financially included - counts respondents who: 
    Have an account registered in thier name or a joint account registered in their name and someone's else in a full-service           bank or
    Have a mobile money account registered in their name or
    Have an account/membership in a full-service non-bank financial institution. 

Levels: 

+ Financially included
+ Financially excluded

## ACTIVE_FINANCIAL		
Active full-service registered account owners- Counts respondents who: 
    Have an account registered in thier name or a joint account registered in their name and someone's else in a full-service           bank and have used the account in the last 90 days before the survey, or
    Have a mobile money account registered in their name and have used it in the last 90 days before the survey, or
    Have an account/membership in a full-service non-bank financial institution and have used it in the last 90 days before the         survey.

Levels: 

+ Yes
+ No

## ACCESS_DFS		
Ever used a digital stored value account - Counts respondents who: 
    Have an account registered in thier name or a joint account registered in their name and someone's else in a full-service           bank that offers digital services, or  use an account that belongs to someone else, or 
    Use a full-service bank account that belongs to someone else
    Have ever used a mobile money service for any financial activity or,
    Have ever used an account/membership in a full-service non-bank financial institution that offers digital services.

Levels: 

+ Yes
+ No 

## REGISTERED_DFS		
Digitally included: counts respondents who: 
    Have an account registered in thier name or a joint account registered in their name and someone's else in a full-service           bank that offers digital services, or   
    Have an account registered in their name with a mobile money service or,
    Have an account/membership in a full-service non-bank financial institution that offers digital services. 

Levels: 

+ Yes
+ No

## ACTIVE_DFS		
Actively use digital stored-value accounts - Counts the same respondents as variable ACCESS_DFS but who used their account in the last 90 days before the survey. 

Levels: 

+ Yes
+ No

## ACTIVE_DFS_ADV		
Actively use digital stored-value accounts and have used at least one advanced financial service (beyond basic wallet & P2P)

Counts the same respondents as variable ACCESS_DFS but who used their account in the last 90 days before the survey to conduct an advanced activity (i.e., activity other than deposit, withdrawal, sending an receiving money). 

Levels: 

+ Yes
+ No

## ACCESS_DFS_PAYMENT_TRANSFER		
Ever used bank or mobile money for digital bill payment or transfer: Counts respondents who have ever used a bank or a mobile money service to pay bills or transfer money. 

Levels: 

+ Yes
+ No

## ACTIVE_FINANCIAL_ADV		
Active use of a registered account for at least one advanced financial service (beyond basic wallet & P2P): Counts respondents who have used their registered full-service bank or NBFI account or their registered mobile money account in the last 90 days to conduct at least one advanced activity (i.e., activity other than deposit, withrdrawal and money tranfer).

Levels: 

+ Yes
+ No

## ACTIVE30_FINANCIAL_ADV		
Active use in the last 30 days of a registered account for at least one advanced financial service (beyond basic wallet & P2P): Counts respondents who have used their registered full-service bank or NBFI account or their registered mobile money account in the last 30 days to conduct at least one advanced activity (i.e., activity other than deposit, withrdrawal and money tranfer).

Levels: 

+ Yes
+ No

## FINANCIAL_STAGE		
Customer journey segmentation

Levels:

+ Nonuser
+ Nonregistered user
+ Inactive registered user
+ Active basic user
+ Active advanced user


