# Mobile Money

Mobile Money Services

## AWARE_MM
Mobile money awareness: counts respondents who are aware of mobile money service.

Levels:

+ 1=Yes
+ 0=No

## AWARE_MM_PROVIDER
Mobile money provider awareness: counts respondents who know at least one mobile money provider.

Levels:

+ 1=Yes
+ 0=No

## AWARE_NONUSER_MM
Nonuser but aware of mobile money: counts respondents who are aware of mobile money service but have never used it.

Levels:

+ 1=Yes
+ 0=No

## ACCESS_MM
Ever use of mobile money: counts respondents who have ever used mobile money service for any financial activity. 

Levels:

+ 1=Yes
+ 0=No

## REGISTERED_MM
Have a mobile money account: counts respondents who have a mobile money registered in their name. 

Levels:

+ 1=Yes
+ 0=No

## ACTIVE_MM
Mobile money use in last 90 days: counts respondents who used their registered mobile money account in the last 90 days.

Levels:
+ 1=Yes
+ 0=No

## ACTIVE30_MM
Mobile money use in last 30 days: counts respondents who used their registered mobile money account in the last 30 days.

Levels:

+ 1=Yes
+ 0=No

## INACTIVE_MM
Inactive mobile user: counts respondents who have not used their mobile money account for any activity in the last 90 days.

Levels:

+ 1=Yes
+ 0=No

## DORMANT_MM
Dormant mobile money account: counts respondents who have never used their registered mobile money account.

Levels:

+ 1=Yes
+ 0=No

## OTC_MM
Nonregistered mobile money users: counts respondents who do not have a mobile money account registered in their name but use mobile money services over the counter. 

Levels:

+ 1=Yes
+ 0=No

## MM_BASIC
Ever use mobile money for basic activities: counts respondents who have used a mobile money account for cash deposit or withdrawal, sending or receiving money, airtime top up, or account management.

Levels:

+ 1=Yes
+ 0=No

## MM_ADV
Ever use mobile money for advanced activities: counts respondents who have used a mobile money account for activities other than cash deposit or withdrawal, sending or receiving money, airtime top up, or account management.

Levels:

+ 1=Yes
+ 0=No

## REG_MM_BASIC
## REG_MM_ADV

## ACTIVE_MM_BASIC
## ACTIVE_MM_ADV
## ACTIVE30_MM_ADV
## LENGTH_MM


## MM_STAGE
Customer journey segmentation for mobile money

Levels:

+ 0="Mobile money nonuser"
+ 1="Unregistered mobile money user"
+ 2="Inactive registered mobile money user"
+ 3="Active mobile money basic user"
+ 4="Active mobile money advanced user"

## MM_TRANSFER
Ever use mobile money for transfer: counts respondents who have ever used mobile money to send or receive money.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_MERCHANT
Ever use of mobile money for purchases: counts respondents who have ever used mobily money to pay for goods and/or services.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_BILL
Ever use of mobile money for bill payment: counts respondents who have ever paid for bills using mobile money.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_GOV
Ever used mobile money to receive money from the government using mobile money.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_WAGE
Ever used mobile money to recieve working wages.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_INSURANCE
Ever used mobile money to pay for insurance or receive benefits.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_SAVE
Ever used mobile money for savings.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_INVEST
Ever used mobile to make an investment.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_LOAN
Ever use mobile money for loans: counts respondents who have ever borrowed money or got credit using mobile money.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## MM_AIRTIME
Ever used mobile money to purchase airtime top-ups or pay for a mobile phone bill.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_TRANSFER
Active use of mobile money transfer: counts respondents who sent or recieved money using mobile money in the last 90 days.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_MERCHANT
Active use of mobile money for purchases: counts respondents who used mobily money to pay for goods and/or services in the last 90 days.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_BILL
Active use of mobile money for bill payment: counts respondents who paid for bills using mobile money in the last 90 days.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_GOV
Used mobile money to receive money from the government in the last 90 days.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_WAGE
Used mobile money in the last 90 days to recieve working wages from an employer.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_INSURANCE
Active use of mobile money for insurance: counts respondents who used mobile money to pay for insurance or receive insurance payments in the last 90 days.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_SAVE
Active use of mobile money for savings: counts respondents who used mobile money to save money in the last 90 days.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_INVEST
Active use of mobile money for investments: counts respondents who used mobile money to make an investment in the last 90 days.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_LOAN
Active use of mobile money for loans: counts respondents who used mobile money in the last 90 days to borrow money or get credit.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## ACTIVE_MM_AIRTIME
Active use of mobile for airtime top-up: counts respondents who used mobile money to purchase airtime top-ups or pay for a mobile phone bill in the last 90 days.

Levels:

+ 1=Yes
+ 0=No
+ 99=Missing

## STM_MM1
Opinion about mobile money services- money is safe and secure

Levels: 

+ 1 = Strongly disagree
+ 2 = Somewhat disagree
+ 3 = Neither disagree, nor agree
+ 4 = Somewhat agree
+ 5 = Strongly agree


## STM_MM2
Opinion about mobile money service- transaction completed without any problem.

Levels: 

+ 1 = Strongly disagree
+ 2 = Somewhat disagree
+ 3 = Neither disagree, nor agree
+ 4 = Somewhat agree
+ 5 = Strongly agree

## STM_MM3
Opinion about mobile money service- Money usually accessible without any problem.

Levels: 

+ 1 = Strongly disagree
+ 2 = Somewhat disagree
+ 3 = Neither disagree, nor agree
+ 4 = Somewhat agree
+ 5 = Strongly agree

## STM_MM4
Opinion about mobile money service- Merchant payment usually accepted without any problem.

Levels: 

+ 1 = Strongly disagree
+ 2 = Somewhat disagree
+ 3 = Neither disagree, nor agree
+ 4 = Somewhat agree
+ 5 = Strongly agree

## STM_MM5
Opinion about mobile money service- Comfortable using it for digital payments to merchants.

Levels: 

+ 1 = Strongly disagree
+ 2 = Somewhat disagree
+ 3 = Neither disagree, nor agree
+ 4 = Somewhat agree
+ 5 = Strongly agree

## STM_MM6
Opinion about mobile money service- Comfortable using it for salaries.

Levels: 

+ 1 = Strongly disagree
+ 2 = Somewhat disagree
+ 3 = Neither disagree, nor agree
+ 4 = Somewhat agree
+ 5 = Strongly agree

## STM_MM7
Opinion about mobile money service- Comfortable using it for cash deposits and withdrawals.

Levels: 

+ 1 = Strongly disagree
+ 2 = Somewhat disagree
+ 3 = Neither disagree, nor agree
+ 4 = Somewhat agree
+ 5 = Strongly agree

## STM_MM8
Opinion about mobile money service- Easier for savings than cash.

Levels: 

+ 1 = Strongly disagree
+ 2 = Somewhat disagree
+ 3 = Neither disagree, nor agree
+ 4 = Somewhat agree
+ 5 = Strongly agree

## EXP_MA1
Experience with mobile money agent -Agent absent

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always


## EXP_MA2
Experience with mobile money agent - Poor customer service

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA3
Experience with mobile money agent - Agent lacks enough money for the transaction

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA4
Experience with mobile money agent - Agent didn't know how perform the transaction

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA5
Experience with mobile money agent - Agent overcharged for transaction

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA6
Experience with mobile money agent -Agent didn't give all the cash due

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA7
Experience with mobile money agent -system/network down

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA8
Experience with mobile money agent -Agent dismissive of women

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA9
Experience with mobile money agent -Agent's place not safe

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA10
Experience with mobile money agent -Agent shared personal/account information with others without consent 

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA11
Experience with mobile money agent - Rude agent

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA12
Experience with mobile money agent -Agent's refusal to perform transaction for no reason

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA13
Experience with mobile money agent -Transaction was time-consuming

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA14
Experience with mobile money agent - Didn't get a receipt

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA15
Experience with mobile money agent -Agent charged for depositing money

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA16
Experience with mobile money agent -Agent asked for PIN number

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA17
Experience with mobile money agent - Agent committed fraud

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXP_MA18
Experience with mobile money agent - Agent's refusal to do transaction due to lack of ID

Levels

+ 1 = Never
+ 2 = Once or twice
+ 3 = Sometimes
+ 4 = Often
+ 5 = Almost always

## EXPSV_MA1
## EXPSV_MA2
## EXPSV_MA3
## EXPSV_MA4
## EXPSV_MA5
## EXPSV_MA6
## EXPSV_MA7
## EXPSV_MA8
## EXPSV_MA9
## EXPSV_MA10
## EXPSV_MA11
## EXPSV_MA12
## EXPSV_MA13
## EXPSV_MA14
## EXPSV_MA15
## EXPSV_MA16
## EXPSV_MA17

## R_NOTUSE_MM1
Reason for not using mobile money - Do not know enough about it

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM2
Reason for not using mobile money - Do not need it

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM3
Reason for not using mobile money - Do not have required documents

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM4
Reason for not using mobile money - Do not have enough money to use it

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM5
Reason for not using mobile money - Do not trust it

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM6
Reason for not using mobile money - Feel like at risk of losing money

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM7
Reason for not using mobile money - Prefer using cash

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM8
Reason for not using mobile money - Fees and expenses are too high 

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM9
Reason for not using mobile money - Can use friend or family member's account  

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM10
Reason for not using mobile money - 

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM11
Reason for not using mobile money - Do not use products and services requiring a registered account 

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM12
Reason for not using mobile money - Do not know how to register an account

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM13
Reason for not using mobile money - No longer have an account 

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM14
Reason for not using mobile money - Prefer using another financial account

Levels:

+ 1= Yes
+ 2= No

## R_NOTUSE_MM15
Reason for not using mobile money - Do not have enough money to use a registered account

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM1
Reason started to use mobile money - Send or receive money

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM2
Reason started to use mobile money - Save money

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM3
Reason started to use mobile money - Have a secure place to store money

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM4
Reason started to use mobile money - Someone else registered an account for me

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM5
Reason started to use mobile money -Borrow money

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM6
Reason started to use mobile money -Make a purchase

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM7
Reason started to use mobile money -Make an investment

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM8
Reason started to use mobile money -Pay a bill

Levels:

+ 1= Yes
+ 2= No

## R_USE_MM9
Reason started to use mobile money - Got an incentive during a promotion

Levels:

+ 1= Yes
+ 2= No

## ACTION_MM1
Opening mobile money menu without asistance

Levels:

+  1=Very difficult
+  2=Somewhat difficult
+  3=Neither difficult, nor easy
+  4=Somewhat easy
+  5=Very easy
+ -2=DK [DO NOT READ]

## ACTION_MM2
Finding a particular mobile money menu option without assistance

Levels:

+  1=Very difficult
+  2=Somewhat difficult
+  3=Neither difficult, nor easy
+  4=Somewhat easy
+  5=Very easy
+ -2=DK [DO NOT READ]

## ACTION_MM3
Completing a mobile money transaction without assistance

Levels:

+  1=Very difficult
+  2=Somewhat difficult
+  3=Neither difficult, nor easy
+  4=Somewhat easy
+  5=Very easy
+ -2=DK [DO NOT READ]

## ACTION_MM4
Correcting an error in the amount of money without assistance

Levels:

+  1=Very difficult
+  2=Somewhat difficult
+  3=Neither difficult, nor easy
+  4=Somewhat easy
+  5=Very easy
+ -2=DK [DO NOT READ]

## ACTION_MM5
Correcting an error in the amount or phone number for a transaction without assistance

Levels:

+  1=Very difficult
+  2=Somewhat difficult
+  3=Neither difficult, nor easy
+  4=Somewhat easy
+  5=Very easy
+ -2=DK [DO NOT READ]

## ACTION_MM6
Reversing or canceling a transaction without assistance.

Levels:

+  1=Very difficult
+  2=Somewhat difficult
+  3=Neither difficult, nor easy
+  4=Somewhat easy
+  5=Very easy
+ -2=DK [DO NOT READ]

## OPN_MM1
Reason for most recent unsuccessful transaction -Technical network problems

Levels:

+ 1= Yes
+ 2= No

## OPN_MM2
Reason for most recent unsuccessful transaction - Agent closed a lunch-break or for the day

Levels:

+ 1= Yes
+ 2= No

## OPN_MM3
Reason for most rececent unsuccessful transaction - I did not have a proper ID
Levels:

+ 1= Yes
+ 2= No

## OPN_MM4
Reason for most recent unsuccessful transaction - There was not enough cash
Levels:

+ 1= Yes
+ 2= No

## OPN_MM5
Reason for most recent unsuccessful transaction - There was not enough float

Levels:

+ 1= Yes
+ 2= No

## OPN_MM6
Reason for most recent unsuccessful transaction - I did not enough money to pay the fee

Levels:

+ 1= Yes
+ 2= No

## AWARE_MMP
## ACCESS_MMP
## REGISTERED_MMP

