# Non-Bank Financial Institutions (NBFIs)

## ACCESS_NBFI 
Access to full-service non-bank financial institutions: counts respondents who have ever used a full-service non-bank financial institution for any financial activity. 

Levels: 

+ Yes  
+ No

## ACCESS_NBFI_ALL
Ever used a non-bank financial institution: counts respondents who have ever used a non-bank financial institution for any financial activity.

Levels:  

+ Yes  
+ No

## REGISTERED_NBFI
Have an account at a full-service non-bank financial institution: counts respondents with an account at a full-service non-bank financial institution.

Levels: 
 
+ Yes  
+ No

## REGISTERED_NBFI_ALL
Have an account with a non-bank financial institution:  counts respondents with an account with any non-bank financial institution.

Levels: 
 
+ Yes  
+ No

## REG_DFS_NBFI
Have a digital stored-value account at a non-bank financial institution: counts respondents with an account/membership at a full-service non-bank financial institution that offers digital features.

Levels: 

+ Yes  
+ No

## ACTIVE_NBFI
Used a full-service non-bank financial account in the past 90 days: counts respondents who have an account/membership with a full-service non-bank financial institution and have used their account in the last 90 days before the survey.

Levels:

+ Yes  
+ No

## ACTIVE_NBFI_ALL
Used a non-bank financial institution in the last 90 days: counts respondents who have an account/membership with any non-bank financial institution and have used their account in the last 90 days before the survey.

Levels:

+ Yes  
+ No

## ACTIVE30_NBFI
Used a non-bank financial institution in the last 30 days: counts respondents who have an account/membership with any non-bank financial institution and have used their account in the last 30 days before the survey.

Levels:

+ Yes  
+ No

## INACTIVE_NBFI
Haven't use a non-bank financial institution in the last 90 days: counts respondents who have an account/membership with any non-bank financial institution and have not used their account in the last 90 days before the survey.

Levels:

+ Yes  
+ No

## DORMANT_NBFI
Dormant NBFI account: counts respondants who have an account with a full-service non-bank financial institution (NBFI) but have never used it for any financial activity.  

Levels:

+ Yes  
+ No

## OTC_NBFI
Nonregistered users of non-bank financial institutions: counts respondents who don't have an account/membership with a non-bank financial institution (NBFI) but have ever used an NBFI for any financial activity. 

Levels:

+ Yes  
+ No

## NBFI_BASIC
Ever use non-bank financial institutions (NBFI) for basic activities: counts respondents who ever used an NBFI for any basic financial activity (deposit, withdrawal, sending or receiving money, or account maintenance). 

Levels:

+ Yes  
+ No

## NBFI_ADV
Ever used a non-bank financial institution (NBFI) for advanced activities: counts respondents who ever used an NBFI for any advanced financial activity (other than deposit, withdrawal, sending or receiving money, or account maintenance). 

Levels:

+ Yes  
+ No

## REG_NBFI_BASIC
Ever use non-bank financial institutions (NBFI) account for basic activities: counts respondents who ever used an NBFI account for any basic financial activity (deposit, withdrawal, sending or receiving money, or account maintenance). 

Levels:

+ Yes  
+ No

## REG_NBF_ADV
Ever used a non-bank financial institution (NBFI) account for advanced activities: counts respondents who ever used an NBFI account for any advanced financial activity (other than deposit, withdrawal, sending or receiving money, or account maintenance). 

Levels:

+ Yes  
+ No

## ACTIVE_NBFI_BASIC
Basic active NBFI account holder: counts respondents who have an account/membership with a full-service non-bank financial institution and have used their account in the last 90 days before the survey to conduct a basic activity (i.e., deposit, withdrawal, sending or receiving money, or account maintenance).

Levels: 
 
+ Yes  
+ No

## ACTIVE_NBFI_ADV
Advanced active NBFI account holder: counts respondents who have an account/membership with a full-service non-bank financial institution and have used their account in the last 90 days before the survey to conduct an advanced activity (i.e., activity other than deposit, withdrawal, sending and receiving money).

Levels: 
 
+ Yes  
+ No

## ACTIVE30_NBFI_ADV
Used own account at a full-service NBFI in the last 30 days to conduct at least one advanced financial service: counts respondents who have a registered account/membership in their name at a full-service NBFI and have used their account in the last 30 days to conduct at least one financial service other than a deposit, withdrawal, sending or receiving money.

Levels:

+ Yes  
+ No

## NBFI_STAGE
Customer journey segmentation for NBFI users: A series of progressive stages through which individuals become more active users of more sophisticated financial services. 

  NBFI stages                  |                       Descriptions
  -----------------------------|---------------------------------------------------------------------------------------------------------------
  NBFI nonuser                 |  Never used a NBFI.
  Unregistered NBFI user       |  Don't have a NBFI account but use NBFI service.
  Inactive registered NBFI user|  Have a NBFI account but have not used it in the last 90 days.
  Active NBFI basic user       |  Have a NBFI account and only used it in the last 90 days for basic activities: cash-in (deposit) or cash-out (withdraw), money transfer to another individual, or conducting account maintenance.
  Active NBFI advanced user   |   Have a NBFI account and used it in the last 90 days for advanced activities (saving, borrowing, insurance, investment, paying bills or receiving wages or government benefits).

Levels:

+ NBFI nonuser
+ Unregistered NBFI user 
+ Inactive registered NBFI user 
+ Active NBFI basic user
+ Active NBFI advanced user

## ACCESS_MFI
Ever used a full-service microfinance institution (MFI): counts respondents who have ever used a full-service MFI.

Levels: 

+ Yes  
+ No

## REGISTERED_MFI
Full-service MFI account ownership: counts respondents who have an account/membership in their name at a full-service microfinance institution.

Levels: 
 
+ Yes  
+ No

## ACTIVE_MFI
Active registered MFI users: counts respondents who have an account/membership at a full-service microfinance institution and have used it in the last 90 days. 

Levels: 
 
+ Yes  
+ No

## ACCESS_COOP
Ever used a full-service cooperative: counts respondents who have ever used a full-service cooperative for any financial activity.

Levels: 
 
+ Yes  
+ No

## REGISTERED_COOP
Full-service cooperative account ownership: counts respondents who have an account/membership in their name at a full-service cooperative.

Levels: 

+ Yes  
+ No

## ACTIVE_COOP
Active registered cooperative users: counts respondents who have an account/membership in thier name at a full-service cooperative and have used it in the last 90 days. 

Levels: 

+ Yes  
+ No

## ACCESS_POST
Ever used a full-service post office bank: counts respondents who have ever used a full-service post office bank for any financial activity.

Levels:

+ Yes  
+ No
 
## REGISTERED_POST
Have a full-service post office bank account:  counts respondents who have an account/membership in their name at a full-service post office bank.

Levels: 
 
+ Yes  
+ No
 
## ACTIVE_POST
Active registered post office bank users: counts respondents who have an account/membership in thier name at a full-service post office bank and have used it in the last 90 days. 

Levels: 
 
+ Yes  
+ No

## ACCESS_SACCO
Ever used a full-service SACCO: counts respondents who have ever used a full-service SACCO for any financial activity.

Levels: 
 
+ Yes  
+ No
 
## REGISTERED_SACCO
Have a full-service SACCO account:  counts respondents who have an account/membership in their name at a full-service SACCO.

Levels: 
 
+ Yes  
+ No
 
## ACTIVE_SACCO
Active registered SACCO users: counts respondents who have an account/membership in thier name at a full-service SACCO and have used it in the last 90 days. 

Levels: 
 
+ Yes  
+ No

## ACCESS_BPR
Ever used a full-service Bank Perkreditan Rakyat(BPR): counts respondents who have ever used a full-service BPR.

Levels: 

+ Yes  
+ No

## REGISTERED_BPR
Have a full-service Bank Perkreditan Rakyat(BPR):  counts respondents who have an account/membership in their name at a full-service BPR.

Levels: 
 
+ Yes  
+ No
 
## ACTIVE_BPR
Active registered Bank Perkreditan Rakyat(BPR) users: counts respondents who have an account/membership in thier name at a full-service Bank Perkreditan Rakyat(BPR) and have used it in the last 90 days. 

Levels: 
 
+ Yes  
+ No
 
## ACCESS_PAWNSHOP
Ever used a full-service Pawnshop: counts respondents who have ever used a full-service Pawnshop.

Levels: 
 
+ Yes  
+ No
 
## REGISTERED_PAWNSHOP
Have a full-service Pawshop:  counts respondents who have an account/membership in their name at a full-service Pawshop.

Levels: 
 
+ Yes  
+ No
  
## ACTIVE_PAWNSHOP
Active registered Pawnshop users: counts respondents who have an account/membership in thier name at a full-service Pawnshop and have used it in the last 90 days. 

Levels: 
 
+ Yes  
+ No
 
## AWARE_PAYMENT_BANK_PROVIDER
Aware payment banks providers: counts respondents who awared payment banks providers.

Levels: 
 
+ Yes  
+ No


## ACCESS_PAYMENT
Ever used a full-service Payment Bank: counts respondents who have ever used a full-service Payment Bank.

Levels: 
 
+ Yes  
+ No
 
## REGISTERED_PAYMENT
Have a full-service payment bank account:  counts respondents who have an account registered in their name or a joint account registered in their name and someone else's at a full-service payment bank.

Levels: 
 
+ Yes  
+ No
  
## ACTIVE_PAYMENT
Active registered payment bank users: counts respondents who have an account in thier name at a full-service payment bank and have used it in the last 90 days. 

Levels: 
 
+ Yes  
+ No
 
## ACCESS_GROUP
Ever used a full-service community savings group: counts respondents who have ever used a full-service community savings group, such as a village savings and loan association.

Levels: 
 
+ Yes  
+ No

## REGISTERED_GROUP
Have a full-service a full-service community savings group account: counts respondents who have a full-service community savings group account, such as a village savings and loan association.

Levels: 
 
+ Yes  
+ No

## ACTIVE_GROUP
Active registered community savings group account users: counts respondents who have a full-service community savings group account and have used it in the last 90 days, such as a village savings and loan association.

Levels: 
 
+ Yes  
+ No

## NBFI_TRANSFER
Ever used non-bank financial institutions (NBFI) to send money to, or receive money from someone: counts respondents who have used their NBFI account to send money to, or receive money from someone.

Levels: 
 
+ Yes  
+ No

## NBFI_MERCHANT
Ever used non-bank financial institutions (NBFI) to buy goods and service: counts respondents who have used their NBFI account to buy goods and service.

Levels: 
 
+ Yes  
+ No

## NBFI_BILL
Ever used non-bank financial institutions (NBFI) to pay bills: counts respondents who have used their NBFI account to pay bills.

Levels: 
 
+ Yes  
+ No
 
## NBFI_GOV
Ever used non-bank financial institutions (NBFI) to receive money from the government: counts respondents who have used their NBFI account to receive money from the government.

Levels: 
 
+ Yes  
+ No

## NBFI_WAGE
Ever used non-bank financial institutions (NBFI) to receive payment from an exmployer: counts respondents who have used their NBFI account to receive payment from an exmployer.

Levels: 
 
+ Yes  
+ No

## NBFI_INSURANCE
Ever used non-bank financial institutions (NBFI) for insurance: counts respondents who have ever used their NBFI account to pay insurance or receive insurance claims.

Levels: 
 
+ Yes  
+ No
 
## NBFI_SAVE
Ever used non-bank financial institutions (NBFI) to save: counts respondents who have ever used their NBFI account to save.

Levels: 

+ Yes  
+ No
 
## NBFI_INVEST
Ever used non-bank financial institutions (NBFI) for investments: counts respondents who have ever used their NBFI account to make investments.

Levels: 
 
+ Yes  
+ No
 
## NBFI_LOAN
Ever used non-bank financial institutions (NBFI) for loans: counts respondents who have ever used their NBFI account to take or repay a loan. 

Levels: 
 
+ Yes  
+ No
 
## ACTIVE_NBFI_TRANSFER
Active use of non-bank financial institutions (NBFI) for sending or receiving money: counts respondents who used their NBFI account to send money to, or receive money from someone in the last 90 days.

Levels: 
 
+ Yes  
+ No

## ACTIVE_NBFI_MERCHANT
Active use of non-bank financial institutions (NBFI) for buying goods and service: counts respondents who used their NBFI account to buy goods and service in the last 90 days.

Levels: 
 
+ Yes  
+ No

## ACTIVE_NBFI_BILL
Active use of non-bank financial institutions (NBFI) for paying bills: counts respondents who used their NBFI account to pay bills in the last 90 days.

Levels: 
 
+ Yes  
+ No

## ACTIVE_NBFI_GOV
Active use of non-bank financial institutions (NBFI) for receiving money from the government: counts respondents who used their NBFI account to receive money from the government in the last 90 days.

Levels: 
 
+ Yes  
+ No

## ACTIVE_NBFI_WAGE
Active use of non-bank financial institutions (NBFI) for receiving payment from an exmployer: counts respondents who used their NBFI account to receive payment from an exmployer in the last 90 days.

Levels: 
 
+ Yes  
+ No

## ACTIVE_NBFI_INSURANCE
Active use of non-bank financial institutions (NBFI) for insurance: counts respondents who used their NBFI account to pay insurance or receive insurance claims in the last 90 days.

Levels: 
 
+ Yes  
+ No
 
## ACTIVE_NBFI_SAVE
Active use of non-bank financial institutions (NBFI) for saving: counts respondents who used their NBFI account to save money for any reason in the last 90 days.

Levels: 
 
+ Yes  
+ No
 
## ACTIVE_NBFI_INVEST
Active use of non-bank financial institutions (NBFI) for investmentse: counts respondents who used their NBFI account for investments in the last 90 days.

Levels: 

+ Yes  
+ No
 
## ACTIVE_NBFI_LOAN
Active use of non-bank financial institutions (NBFI) for loans: counts respondents who used their NBFI account to take or repay a loan in the last 90 days.

Levels: 
 
+ Yes  
+ No
 
