# Loans

Loans

## LOAN
Ever borrowed money: counts respondents who have ever borrowed money outside their household

Levels: 

+ 1="Yes"
+ 0= "No"
+ 99= "Don't know"

## LOAN_CURRENT
Currently have a loan with at least one organization: counts respondents who currently have a loan with any organisation. 

Levels: 

+ 1="Yes"
+ 0= "No"
+ 99= "Don't know"

## LOAN_INTEREST
Know interest rate paid on loans: counts who currently have a loan and know the interest rate they pay on the loan.

Levels: 

+ 1="Yes"
+ 0= "No"
+ 99= "Don't know"

## LOAN_INFML
Ever borrowed from an informal source: counts respondents who ever borrowed from a store, shopkeeper, private moneylender, pawnshop or a self help group or cooperative without having a membership.

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_FORMAL

## LOAN_STORE
Ever borrowed from a store or shopkeeper: counts respondents who have ever purchased something from a store or shopkeeper using credit. 

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_CREDITCARD
Ever purchased using a credit card: counts respondents who have ever purchased something using a credit card.

Levels: 
+ 1="Yes"
+ 0= "No"

## LOAN_BANK
Ever borrowed money or used credit from a bank

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_MM
Ever borrowed money or used credit from a mobile money service.

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_MFI
Ever borrowed money or used credit from a microfinance institution

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_COOP
Ever borrowed money or used credit from a cooperative

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_MLENDER
Ever borrowed money from a private moneylender

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_PAWN
Ever borrowed money from a pawnshop

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_GROUP
Ever borrowed money from a village savings and loan association

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_POST
Ever borrowed money from a post office bank

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_PAYBANK
Ever borrowed money from a payments bank

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_SACCO
Ever borrowed money from a SACCO

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_EMERGENCY
Borrowed money for emergency expenses: counts respondents who have borrowed money in the 12 months to pay for emergency expenses such as medical bills.

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_DAILY
Borrowed money for daily expenses: counts respondents who have borrowed money in the last 12 months to pay for daily expenses (e.g, fodd, transportation)

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_BUSINESS
Borrowed money for business expenses: counts respondents who have borrowed money in the last 12 months to pay for business expenses or invest in a business.

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_HOME
Borrowed money for home improvement: counts respondents who have borrowed money in the last 12 months to invest in home improvement or construction.

Levels: 

+ 1="Yes"
+ 0= "No"

## LOAN_AGRIC
Borrowed for agricultural inputs: counts respondents who have borrowed money in the last 12 months to pay for agricultural inputs. 

Levels: 

+ 1="Yes"
+ 0= "No"
