# Savings



## SAVE
Ever saved money

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_KNOW_INTEREST
Know interest rate on saving: counts repondents who have ever saved money and know the interest rate earned on their savings.

Levels: 

+ 1="Yes"
+ 0= "No"

Notes:

* This variable is only available for 2016 and 2017.

## SAVE_INFML
Ever saved with informal channels: counts respondents  who have ever saved money with people they trust (e.g., family, friends, neighbors, shopkeepers, money guards, savings collectors) or with a self-help group or cooperative without membership.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_FORMAL 
Ever saved with formal institutions: counts respondents who have ever saved with a bank, payments bank, post office bank, microfinance institution, mobile money service, smartphone application, or their account at a self-help group or cooperative. 

Levels: 

+ 1 = "Yes"
+ 0 = "No"

## SAVE_BANK
Ever saved with a bank: counts respondents who have ever saved with a bank, or put money in savings using a smartphone application or the menu of a mobile phone.

Levels: 

+ 1 = "Yes"
+ 0 = "No"

## SAVE_MM
Ever saved using mobile money: counts respondents who have ever saved using a mobile money service.

Levels: 

+ 1 = "Yes"
+ 0 = "No"

## SAVE_MFI
Ever saved with a microfinance institution (MFI): counts respondents who have ever saved using an MFI.

Levels: 

+ 1 = "Yes"
+ 0 = "No"

## SAVE_COOP
Ever saved with a cooperative: counts respondents who have ever saved using a cooperative.

Our definition of a cooperative is any financial organization owned by its members, such as a credit union, or a Savings and Credit Co-operative Society (SACCO).

The country definition, however, varies.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_GROUP
Ever saved with a saving groups.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_POST
Ever saved with post office bank: counts respondents who ever have saved with a post office bank.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_CASH_PROPERTY
Ever saved wiht cash or property: counts respondents who save through buying something (e.g., agricultural inputs, livestock, gold or other valuable things) or in cash at home or on themselves. 

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_BUSINESS
Save for business: counts respondents who save to start or expand their own business.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_EDUCATION
Save for own education: counts respondents who save for their educational purposes.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_RETIREMENT
Save for retirement: counts respondents who save in order to get ready for retirement.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_PRESTIGE
Save for prestige: counts respondents who save in order to buy expensive and prestigious things such as an expensive car, jewelry, designer clothes, high-end electonics or a big house. 

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_SECURITY
Save for security: counts respondents who save to protect their families from poverty and crime or protect their belongings.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_EMERGENCY
Save for emergencies: counts respondents who save for emergency expenses.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_DAILY
Save for dialy expenses: counts respondents who save to just make ends meet on a daily basis.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_COMMUNITY
Save for community: counts respondents who save money to give back to their community or create a charitable organization. 

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_CHILDREN_EDU
Save for children's education: counts respondents who save to build their children's education fund.

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_WEDDING
Save for wedding: counts respondents who save to build children's fund for wedding (ceremony and/dowry).

Levels: 

+ 1="Yes"
+ 0= "No"

## SAVE_HOUSE
Save for house: counts respondents who save to buy or build a house.

Levels: 

+ 1="Yes"
+ 0= "No"
