# Financial Health



## HAVE_PLAN
Have a financial plan for unexpected events.

Levels:

+ 1=Yes
+ 0=No

Notes:

* This data is only available for 2016 and 2017.
* In 2017, these questions were asked on a 5-point Likert scale instead of yes/no. The options "Somewhat Agree" and "Strongly Agree" were converted to the "Yes" level.

## ECO_VUL
This variable uses multiple questions within surveys to determine if the respondent is economically vurlnerable.

Notes:

* This data is only available for 2016 and 2015.

## FIN_SHOCK
Financial shock: counts respondents who, within the last two years, experienced a shock such as fire, flood, natural disaster, burglary, pests,  job loss, death of main income earner, increase costs of agricultural inputs, drop in crop or livestock price, large medical expenses or family separation. 

Levels:

+ 1=Yes
+ 0=No

Notes:

* This data is only available for 2016 and 2015.

## BUDGET_INCOME
Plan how to spend income.

Levels:

+ 1=Yes
+ 0=No

## BUDGET_STAY
Stay on budget: counts respondents who make a plan for how to spend thier income and keep the plan

Levels:

+ 1=Yes
+ 0=No

## FIN_HEA1
Have goals to achieve for next few months: count respondents who have goals for the next few months they want to achieve with thier money. 

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA2
Have enough money for living expenses: counts respondents who have enough money to pay for their living expenses.

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA3
Spend less than what they make: counts respondents who spend less money than they make each month.

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA4
Pay bills on time and in full

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA5
Have emergency fund for unplanned expenses: counts respondents who have an emergency fund that is large enough to cover unplanned expenses. 

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA6
Confidence in future income growth: counts respondents who are confident that their income will grow in the future. 

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA7
Earn enough to pay debt and expenses: counts respondents who earn enough money to pay back debt and pay for living expenses.

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA8
Friends and family reply on me to help with their finances

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA9
Have financial security: counts respondents who have savings or assets that will keep them financially secure in the future. 

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_HEA10
Have skills and knowledge to manage finances well.

Levels:

+ 1=Strongly disagree
+ 2=Somewhat disagree
+ 3=Neither disagree, nor agree
+ 4=Somewhat agree
+ 5=Strongly agree

## FIN_SHO1
Household gone without food: counts respondents whose households have ever gone without enough food to eat in the last 6 months. 

Levels:

+ 1=Yes
+ 0=No

## FIN_SHO2
Household gone without cooking fuel: counts respondents whose households have ever gone without fuel to cook food.

Levels:

+ 1=Yes
+ 0=No

## FIN_SHO3
Household gone without medical care: counts respondents whose households, in the last 6 months needed a doctor but delayed or went  without because of a shortage of funds.

Levels:

+ 1=Yes
+ 0=No

## FIN_SHO4
Household gone without veterinarian care: counts respondents whose households, in the last 6 months needed a veterinarain or vet medicine but went without because of a shortage of funds.

Levels:

+ 1=Yes
+ 0=No

## FIN_SHO5
Household gone without fertilizer: counts respondents who households, in the last 6 months need fertilizer for the farm but went without because of a shortage of funds.

Levels:

+ 1=Yes
+ 0=No

## FIN_SHO6
Could not buy stock for business:  counts respondents whose households, in the last 6 months needed stock for the business but could not buy any because of a shortage of funds, and had to close down temporarily or completely. 

Levels:

+ 1=Yes
+ 0=No

## FIN_SHO7
Household experienced unpaid school fees: counts respondents whose households had a child sent home from school in the last 6 months because of unpaid school fees. 

Levels:

+ 1=Yes
+ 0=No

## FIN_SHO8
Household missed a family or life event: counts respondents whose households had to miss a family or life event (e.g., funeral, wedding) in the last 6 months because they couldn't pay for transportation. 

Levels:

+ 1=Yes
+ 0=No

## MONEY_SOU1
Sold agricultural products or reared livestock: counts respondents who got money in the last 12 months by selling agricultural products or rearing livestock. 

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU2
Received assistance from the government in the past 6 months

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU3
Received money a relative, friend, or another person inside the country in the past 6 months

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU4
Received money from a relative, friend, or another person from a foreign country in the past 6 months

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU5
Got money in the past 6 months from ownership of a business, property or assets.

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU6
Got money in the past 6 months from employment by the government

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU7
Got money in the past 6 months from employment in a business with less than 10 employees

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU8
Got money in the past 6 months from employment in a business with more than 10 employees

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU9
Got money in the past 6 months from a scholarship or stipend from the government or educational institution.

Levels:

+ 1=Yes
+ 2=No

## MONEY_SOU10
Got money in the last 6 months from pension

Levels:

+ 1=Yes
+ 2=No

## EXPENSE1, EXPENSE2, EXPENSE3
Respondents were asked how they would spend extra money left over at the end of the month across several categories.

Values:

Value | Label
--- | ---
1 | Saving money, 
2 | Investing in your existing business, 
3 | Repaying any existing debts, 
4 | Sending money to other people, including sending regular support money, emergency support, gifts, etc.,
5 | Spending on farm (e.g., lease more land, buy fertilizer or pesticides, buy seeds), 
6 | Buying the family some clothes/something nice for the home, 
7 | Buying better food, 8. Buying more of your usual foods, 
9 | Invest in assets like shares, real estate, jewelry, 
10 | Entertainment (e.g., movies, restaurants, sport shows, theater, restaurants, clubbing, partying), 
11 | I don’t want to spend on anything else

Notes:

* These variables are only available for 2015 and 2016.
* In 2014, these questions were asked regarding the past, rather than a hypothetical situation, and aren't equivalent.
* For 2015, "other" was not an option and in 2016 it was. "Other" coding was excluded.
* For PAkistan in 2015, Don't know/Refused was an option. This has been coded "99".
